import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <nav>
          <Navbar/>
        </nav>
        {children}
        </body>

      <Script src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js" />
      <Script src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js" />
      <Script src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js" />
    
    </html>
  );
}
